name: bizcard_app
description: "A Business digital card app."

publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=3.2.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  #icons
  antdesign_icons: ^0.0.3

  #image
  cached_network_image: ^3.3.1
  image_picker: ^1.0.5
  image_cropper: ^5.0.1

  #internationalize
  intl: ^0.19.0

  #local-storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  #network
  connectivity_plus: ^5.0.2
  dio: ^5.4.0

  #SML
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3

  #style
  google_fonts: ^6.1.0

  #utils
  bot_toast: ^4.1.3
  share_plus: ^7.2.1

  #widgets
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "res/images/app_logo.jpg"
  web:
    generate: false
  windows:
    generate: false
  macos:
    generate: false

flutter:

  uses-material-design: true

  assets:
    - res/images/
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
