name: Flutter APK - Staging release

# Controls when the action will run. Triggers the workflow on push events
# but only for the main branch
on:
  push:
    branches: 
      - staging

jobs:
  build_and_deploy:
    env:
      KEY_PROP: ${{ secrets.KEY_PROPERTIES }}
      KEY_JKS: ${{ secrets.KEY_JKS }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Get current date time
        run: echo "current_date_time=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2.8.0
        with:
          channel: 'stable'
          cache: true
          # flutter-version: '3.7.12'
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:' # optional, change this to force refresh cache
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:' # optional, change this to specify the cache path
          architecture: x64 # optional, x64 or arm64
      - run: echo "${{ secrets.KEY_PROPERTIES }}" > android/key.properties
      - run: echo "${{ secrets.KEY_JKS }}" | base64 --decode > android/app/store.jks
      - run: flutter pub get
      - run: flutter build apk --release --target-platform android-arm,android-arm64 --split-per-abi --flavor dev
      # - name: send telegram message on push
      #   uses: appleboy/telegram-action@master
      #   with:
      #     to: ${{ secrets.TELEGRAM_TO }}
      #     token: ${{ secrets.TELEGRAM_TOKEN }}
      #     message: "Dev Build APK release ${{ env.current_date_time }}"
      #     document: build/app/outputs/flutter-apk/app-arm64-v8a-dev-release.apk
      - name: Upload to Google Drive
        uses: gdrive-org/upload-action@staging
        with:
          serviceAccountKey: ${{ secrets.GOOGLE_DRIVE_SERVICE_ACCOUNT_KEY }}
          filePath: 'build/app/outputs/flutter-apk/app-arm64-v8a-dev-release.apk'
          parentFolder: '1TX513gIaZB88Md62a53jycj6CawbgTYw'
          folderName: 'APKs'
          recursiveSearch: true
      